---

- name: Install vim
  pacman:
    name: vim
    state: present

- name: Install vscodium
  aur:
    name: vscodium-bin
    user: "{{ user.name }}"

- name: Install vscodium extensions
  ansible.builtin.command: "vscodium --install-extension {{ item }}"
  become_user: "{{ user.name }}"
  register: ext_install
  changed_when: ext_install.rc != 0
  with_items:
    - asciidoctor.asciidoctor-vscode
    - gulajavaministudio.mayukaithemevsc
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
    - waderyan.gitblame
